### ISSUE TITLE
Site Down?

### ISSUE THREAD

**Issue by hhsnopek** [itsabot/itsabot.org#11]
It appears the site is down? Apr 14 @ 8:21PM

**Comment by egtann** [comment]
It was down for me via router settings earlier, but available elsewhere. I'll keep looking into this. And if anyone has experience with sys admin work, let me know! 🙂

**Comment by egtann** [comment]
I'm also still able to access the site right now. But something is definitely up

**Comment by hhsnopek** [comment]
Looks like it's up 😄 - shall we close this out?
